create schema Mithron_bank;

use Mithron_bank;

SELECT * FROM DIM_CUSTOMERS;
-- GENDER WISE CUSTOMER
SELECT GENDER, COUNT(*) AS NUMBER, ROUND(100*COUNT(GENDER)/SUM(COUNT(GENDER)) OVER()) AS PERCENTAGE
FROM DIM_CUSTOMERS GROUP BY GENDER;

-- CUSTOMERS - AGE_GROUP
SELECT AGE_GROUP, COUNT(*) AS NUMBER, ROUND(100*COUNT(AGE_GROUP)/SUM(COUNT(AGE_GROUP)) OVER()) AS PERCENTAGE
FROM DIM_CUSTOMERS GROUP BY AGE_GROUP ORDER BY AGE_GROUP;

-- CUSTOMERS MARITAL STATUS
SELECT `marital status`, COUNT(*) AS `NUMBER OF CUSTOMERS`, ROUND(100*COUNT(*)/SUM(COUNT(*)) OVER(),1) AS PERCENTAGE
FROM DIM_CUSTOMERS GROUP BY `marital status` ORDER BY `marital status`;

-- CUSTOMERS - OCCUPATION
SELECT occupation AS OCCUPATION,
COUNT(*) AS `NUMBER OF CUSTOMERS`,
ROUND(100* COUNT(*)/SUM(COUNT(*)) OVER()) AS `PERCENTAGE`
FROM DIM_CUSTOMERS GROUP BY OCCUPATION ORDER BY `NUMBER OF CUSTOMERS` DESC; 

-- CUSTOMER - CITY
SELECT CITY, 
COUNT(*) AS `NUMBER OF CUSTOMERS`,
ROUND(100*COUNT(*)/SUM(COUNT(*)) OVER()) AS `PERCENTAGE`
FROM DIM_CUSTOMERS GROUP BY CITY ORDER BY COUNT(*) DESC;

-- AVERAGE MONTHLY INCOME
SELECT ROUND(AVG(C.AVG_INCOME)) AS `AVERAGE INCOME`,
ROUND(AVG(S.SPEND),2) AS `AVERAGE vALUE OF TRANSACTION` 
FROM DIM_CUSTOMERS C
JOIN FACT_SPENDS S ON C.CUSTOMER_ID=S.CUSTOMER_ID;

WITH CTE AS 
(SELECT S.MONTH, SUM(S.SPEND) AS `TOTAL SPEND` FROM FACT_SPENDS S GROUP BY S.MONTH)
SELECT AVG(`TOTAL SPEND`) FROM CTE;

-- TOTAL SPEND 
SELECT SUM(SPEND)/1000000 FROM fact_spends;


SELECT * FROM fact_spends;
SELECT AVG(SPEND), CUSTOMER_ID FROM fact_spends GROUP BY customer_id;


SELECT SUM(SPEND) AS TOTAL_SPEND ,CUSTOMER_ID, `MONTH` FROM fact_spends GROUP BY customer_id,month ORDER BY customer_id;

WITH CTE AS 
(SELECT SUM(SPEND) AS TOTAL_SPEND ,CUSTOMER_ID, `MONTH` FROM fact_spends GROUP BY customer_id,month)
SELECT AVG(TOTAL_SPEND), CUSTOMER_ID  FROM CTE GROUP BY CUSTOMER_ID ORDER BY CUSTOMER_ID;
